### ISSUE TITLE
Add a .gitignore file to prevent tracking of the intermediate and saved directories

### ISSUE THREAD

**Issue by arkanes** [UE4-OceanProject/OceanProject#1]
The Intermediate and Saved directories just store editor state and backups as you imagine, they add a lot of space to the repo and aren't required.

These are the UDK .gitignore entries I use:
# UDK files

/Binaries
/DerivedDataCache
/Intermediate
/Saved
*.opensdf

**Comment by Nsomnia** [comment]
I was going to ask if he was going to add a .gitignore. I dont use one because I'm worried if my partners pulls a copy of the repo it wont run becuse the /binarys /intermediate and /saved is needed. Anyone have any idea on a .gitignore for unreal 4? Theres little documentation out there.

**Comment by arkanes** [comment]
Intermediate and saved are definitely not needed - that's temp files the editor uses for itself and autosaved backups.

**Comment by Nsomnia** [comment]
Added those dirs, will see what happens becuse intermediate keeps the precompiled header files for the ocean project I want to keep the local files so they are still showing up under unstaged in sourcettree. will seee what happens next push.

**Comment by dotcamdev** [comment]
I removed all of the files from the intermediate & saved folders to save some space in the last commit to master yesterday, there are a few other fixes I want to add before merging it back over to 1.0 (looks like I did that too soon). I only removed the backup saves, logs, etc, and left the config files just in case.

So using a gitignore is another way around this? I'll look into that. Thanks

**Comment by Nsomnia** [comment]
when adding a .gitignore file (no extension just periodgitignore) to your root repo folder tells git to ignore any files in the future commits. Heres mine

```
# Compiled Object files *.obj  .obj is a model file format I use sometimes
*.slo
*.lo
*.o

# Precompiled Headers will require recompiling with every pull if we work in the working directory so... have to think about this one the .pch is 500 mb
*.gch
*.pch

# Compiled Dynamic libraries *.dll should need dlls for plugins
*.so
*.dylib

# Fortran module files dont think well use fortran lol commenting this out *.mod

# Compiled Static libraries
*.lai
*.la
*.a
*.lib

# Executables
*.out
*.pp

#Blender Simulations
*.bphys

# Blender Autosaves
*.blend1

# Unreal temp files
Intermediate/
Saved/
gameMain/Intermediate/
gamemain/Saved/

# if this doesnt work may need to set the files weve already commmited int hose directorys (tracked) to untracked using files #tracked before can be untracked by running git rm --cached filename


# Windows
Thumbs.db
*.log
*.tmp
Models/UV Unwraps/Subs/USA/SSN571/ssn571_bridge_ALLMAPS_6k.psd
```

**Comment by dotcamdev** [comment]
Sorry for the delay on this, but a .gitignore file has now been added. Up to this point I have been manually removing the files, but this should make things easier.

Thanks!
