### ISSUE TITLE
Not working on 4.22

### ISSUE THREAD

**Issue by tareq0065** [UE4-OceanProject/OceanProject#106]
It's not working at v4.22. is there any way? Its always showing that its build from another version. Is anybody has the build version for the 4.22 or what will be the instruction to do it? This is a very good project, obviously. I am new to UE. I am clearly not telling that, this is an error or issue.

**Comment by ADS-Astral** [comment]
The diftow-testbranch has a working 4.22 version. When you download the project from that branch it has a 4.22 ocean project as default. 
![image](https://user-images.githubusercontent.com/32249404/61912185-c3f61280-af7c-11e9-802d-47cc1ec9d6b1.png)

**Comment by EvoPulseGaming** [comment]
I believe it was 4.22 preview 4, and now that 4.22 is final, this project needs to be re-compiled and a new commit needs to be pushed. (I'm working on a test branch right now, if someone could compile the master branch to the latest 4.22 and submit a pull request that would be great)

Please note that the diftow-testbranch is a branch that I personally am  working on, its the "preview" of what is to come. (I need help with some advanced math/gimbal lock/ 2d to 3d transform material, before I will continue with this branch, (((This is for the sun/moon system))))
