### ISSUE TITLE
Remove old compute shader

### ISSUE THREAD

**Issue by ctankep** [UE4-OceanProject/OceanProject#108]
Master branch contains :
" Plugins/ComputeShaderDev "

Though this causes an error when trying to rebuild from
the external submodule. Using later versions of UE 4.x and 
so on. The existing file causes UE to exit and fail the 
shader build process.

**Comment by EvoPulseGaming** [comment]
It's not old, it's an example compute shader for the ocean project for others to use to contribute to the project.... It needs to be updated

**Comment by ctankep** [comment]
Np , am happy to update in the submodule and
put in a PR there. I guess resolving #107 needs this to 
be complete.

**Comment by EvoPulseGaming** [comment]
106# was already resolved and pushed to both master and master final.
