### ISSUE TITLE
crash when opening project on mac os x mojave

### ISSUE THREAD

**Issue by mustafaghali** [UE4-OceanProject/OceanProject#111]
I tried version 19/20/22 with the corresponding versions UE4 of 19/20/22 but it always crash on the start, does this happen to all users ? am I missing any necessary installation requirement ?

**Comment by EvoPulseGaming** [comment]
I've submitted a fix for another issue, it might not be related but give it a shot. Also post logs please

**Comment by EvoPulseGaming** [comment]
20 days old, no response. Will close. Please comment and I will re-open
