### ISSUE TITLE
Cooking and packaging issues for Windows X64

### ISSUE THREAD

**Issue by chase03** [UE4-OceanProject/OceanProject#115]
is anybody showing like those issues when you cook and packaging for windowsX64
And is failed for package for Windows X64, by the way on the development mode

PIE: Error: Blueprint Runtime Error: "Accessed None reading structure Second". Blueprint:  WB_Sky_HUD Function:  Get Text Time Graph:  GetText_Time Node:  Return Node
PIE: Error: Blueprint Runtime Error: "Accessed None trying to read property SkyRef". Blueprint:  WB_Sky_HUD Function:  Get Text Solar Time Graph:  GetText_SolarTime Node:  Return Node
PackagingResults: Error: [Compiler ThirdPersonGameMode] Could not find a function named "SendMsgToClient" in 'ThirdPersonGameMode'.

**Comment by EvoPulseGaming** [comment]
Can you post the log?

**Comment by EvoPulseGaming** [comment]
Also you can find us here: https://discord.gg/ewadNBG

**Comment by KamikazeXeX** [comment]
> is anybody showing like those issues when you cook and packaging for windowsX64
> And is failed for package for Windows X64, by the way on the development mode
> 
> PIE: Error: Blueprint Runtime Error: "Accessed None reading structure Second". Blueprint: WB_Sky_HUD Function: Get Text Time Graph: GetText_Time Node: Return Node
> PIE: Error: Blueprint Runtime Error: "Accessed None trying to read property SkyRef". Blueprint: WB_Sky_HUD Function: Get Text Solar Time Graph: GetText_SolarTime Node: Return Node
> PackagingResults: Error: [Compiler ThirdPersonGameMode] Could not find a function named "SendMsgToClient" in 'ThirdPersonGameMode'.

The error is right there, Could not find a function named "SendMsgToClient" in 'ThirdPersonGameMode'.

Check over your project for references to SendMsgToClient (use the Find in Blueprints feature from Developer Tools) and remove them, it seems like something from the built in chat system is missing so that's a good place to start looking.

**Comment by EvoPulseGaming** [comment]
No reply, assuming this was the correct answer
