### ISSUE TITLE
The ocean project in UE 4.23 is causing constant crash . 

### ISSUE THREAD

**Issue by Fearcry** [UE4-OceanProject/OceanProject#116]
The project after a while running causing constant crash :/
[MyProject.log](https://github.com/UE4-OceanProject/OceanProject/files/3851248/MyProject.log)

**Comment by EvoPulseGaming** [comment]
This log only has 3 minutes of runtime in it.......

Apart from that, the only reference to an error I found was in another language, which translated to:
Operation completed successfully.

You need to find the correct log that shows the error

**Comment by EvoPulseGaming** [comment]
No reply, closing
