### ISSUE TITLE
Editing Ocean Amplitude doesn't work after packaging

### ISSUE THREAD

**Issue by CapnNickSparrow** [UE4-OceanProject/OceanProject#117]
See title, the preview windows and engine window the ocean height is perfect, but after packaging it keeps resetting

**Comment by djelom** [comment]
Just jumping in here, do you mean the height map that is used to scale the waves? 
If so, did you add the directory were the height map is into the elements that need to be packaged? It's in "Additional Asset Directories To Cook"

**Comment by dotcamdev** [comment]
Note to self, add to discord FAQ

**Comment by CapnNickSparrow** [comment]
If you mean add the ocean folder to cooking, yes I did, but still the ocean waves are high compared to the engine

**Comment by CapnNickSparrow** [comment]
Ingame:
![image](https://user-images.githubusercontent.com/37894150/69042386-66854600-09f1-11ea-9e6d-051427638eb7.png)

In Engine:
![image](https://user-images.githubusercontent.com/37894150/69042579-bbc15780-09f1-11ea-8598-de2ba167861b.png)

Settings Ocean and Package:
![image](https://user-images.githubusercontent.com/37894150/69042703-f88d4e80-09f1-11ea-9caf-0da1dbeae265.png)

![image](https://user-images.githubusercontent.com/37894150/69042725-06db6a80-09f2-11ea-8b87-5511ac8481a2.png)

**Comment by EvoPulseGaming** [comment]
What was the solution for this?

**Comment by EvoPulseGaming** [comment]
This user is in the discord as of 03/26/2020, as seems to be using the plugin fine. I'm closing this
