### ISSUE TITLE
Unreal 4.24.1 - black water

### ISSUE THREAD

**Issue by tomaszzackiewicz** [UE4-OceanProject/OceanProject#123]
Hello,

I wish to report that there are some problem with UE 4.24:

![image](https://user-images.githubusercontent.com/5631906/71560409-e3ccbd80-2a69-11ea-9d31-46488141cd2a.png)

**Comment by tomaszzackiewicz** [comment]
[OceanProject.log](https://github.com/UE4-OceanProject/OceanProject/files/4008385/OceanProject.log)

**Comment by EvoPulseGaming** [comment]
Visit the #FAQ channel in the discord for solutions to known issues like this.
