### ISSUE TITLE
Packaging failed for Windows x64 on UE4.24

### ISSUE THREAD

**Issue by chase03** [UE4-OceanProject/OceanProject#125]
![微信图片_20200303233451_看图王](https://user-images.githubusercontent.com/26050994/75791974-5038a580-5da8-11ea-87b3-be2398d4eb3b.jpg)

Packaging failed for Windows x64 on UE4.24, could you help me out, thanks!
Here is the error information

**Comment by EvoPulseGaming** [comment]
Something wrong with the way you imported the blueprints. This is not a problem without project. Visit the unreal forums, or discord for assistance
