### ISSUE TITLE
ocean disappeared after packaging

### ISSUE THREAD

**Issue by hustsdy** [UE4-OceanProject/OceanProject#126]
The plugin is powerful,but i suffer a problem.I follow the installation setup the plugin in a new project,it's normal in the editor,but when packaging it in 4.23,the ocean disappeared .here post 2 pics:
can u help to solve the peoblem,tks.
![in editor](https://user-images.githubusercontent.com/18216040/75854083-52dbdf00-5e2a-11ea-84df-19eec8eddb1c.png)
![win64 program](https://user-images.githubusercontent.com/18216040/75854104-5c654700-5e2a-11ea-96c1-3e0dfe2a9ecb.png)

**Comment by EvoPulseGaming** [comment]
You must have a c++ project in order for this project to package correctly. Let me know if you still have issues

"Right, so, in case anyone is running into the same trouble I had: When you have a pure blueprint project, and you want to use the ocean plugin, but you can't execute your packaged builds, add one simple, empty C++ to your project, let Unreal do it's magic, package your game again and voila, you can run your packaged game"
