### ISSUE TITLE
Black water shading in 24.3

### ISSUE THREAD

**Issue by VBlake1** [UE4-OceanProject/OceanProject#128]
Hello, I opened the project in ue 24.3 version, and the water shading is completly black, waves working fine as well as all movement, only happens with water. I opened the project in ue 23 version and all works fine. Imcompatibility with version? or something changed about the light or reflections (That's why I think it could be) in this version?

Thanks.

**Comment by EvoPulseGaming** [comment]
Visit the #faq channel in discord for fixes with known issues: https://discord.gg/Xzrbpup
