### ISSUE TITLE
Executable doesn't launch

### ISSUE THREAD

**Issue by MilanDierickGD** [UE4-OceanProject/OceanProject#130]
Using UE4 4.24.3, I've got a project set up with the Ocean plugin, without changing anything about my packaging settings, and without moving the plugin to the Engine/Runtime folder of UE, I package my project, but when executing the generated executable, literally nothing happens... No error message pops up, no error pops up while packaging as far as I can see, not sure if I need to configure anything else to package this properly.

**Comment by EvoPulseGaming** [comment]
So the install.md file was a bit wrong about some things. Please visit the discord link in the readme, find the #faq channel, and follow the guides there, as they are updated.
