### ISSUE TITLE
Error when packaging: System.ArgumentException: An item with the same key has already been added. 

### ISSUE THREAD

**Issue by MilanDierickGD** [UE4-OceanProject/OceanProject#131]
Still the same project from my previous issue, UE4 4.24.3, this time around I copied the plugin folder to the runtime folder in the unreal engine folder. Applying the change to the project file in the plugin folder described in the INSTALL file doesn't change the error here. I go into my project, go and package my project for windows 32 / 64 bit, and pretty much instantly Unreal throws that error and stops the packaging process, logs are minimal, will post them in a bit if needed. 

I'm sure that I missed something, but I don't know what?

**Comment by EvoPulseGaming** [comment]
We solved this on discord. For everyone else, this is because the plugin was installed twice, once in his project, and again in the engine.

**Comment by bbacle** [comment]
This did not solve the problem for me. I still get the same error even after disabling the plugin in my project.

**Comment by JiveyGuy** [comment]
> This did not solve the problem for me. I still get the same error even after disabling the plugin in my project.

Based on the previous replies, you should probably uninstall both and simply install to your project.
