### ISSUE TITLE
Packaging for HTML5  not working 

### ISSUE THREAD

**Issue by FeliciaBrisc** [UE4-OceanProject/OceanProject#132]
Hi guys,  
Packaging with UE 4.22/Windows10 for HTML5 appears to be not working  - it works with no problems for Windows and Linux, and the Apex Plugin is enabled.  How could this be solved? 
Thanks.

>  Packaging (HTML5):     D:\UNREAL\MOW_PROJECT_RELOAD\MOW_PROJECT_RELOAD\Plugins\OceanPlugin\Source\OceanPlugin\Private\BuoyantDestructibleComponent.cpp(83,22):  error: use of undeclared identifier 'ApexDestructibleActor'
UATHelper: Packaging (HTML5):             uint32 ChunkCount = ApexDestructibleActor->getNumVisibleChunks();
UATHelper: Packaging (HTML5):                                 ^
UATHelper: Packaging (HTML5):     D:\UNREAL\MOW_PROJECT_RELOAD\MOW_PROJECT_RELOAD\Plugins\OceanPlugin\Source\OceanPlugin\Private\BuoyantDestructibleComponent.cpp(84,31):  error: use of undeclared identifier 'ApexDestructibleActor'
UATHelper: Packaging (HTML5):             const uint16* ChunkIndices = ApexDestructibleActor->getVisibleChunks();
UATHelper: Packaging (HTML5):                                          ^
UATHelper: Packaging (HTML5):     D:\UNREAL\MOW_PROJECT_RELOAD\MOW_PROJECT_RELOAD\Plugins\OceanPlugin\Source\OceanPlugin\Private\BuoyantDestructibleComponent.cpp(87,27):  error: use of undeclared identifier 'ApexDestructibleActor'
UATHelper: Packaging (HTML5):                     PxRigidDynamic* Chunk = ApexDestructibleActor->getChunkPhysXActor(ChunkIndices[c]);
UATHelper: Packaging (HTML5):                                             ^
UATHelper: Packaging (HTML5):     3 errors generated.
UATHelper: Packaging (HTML5):     shared:ERROR: compiler frontend failed to generate LLVM bitcode, halting
PackagingResults: Error: use of undeclared identifier 'ApexDestructibleActor'
PackagingResults: Error: use of undeclared identifier 'ApexDestructibleActor'
PackagingResults: Error: use of undeclared identifier 'ApexDestructibleActor'
PackagingResults: Error: compiler frontend failed to generate LLVM bitcode, halting

**Comment by EvoPulseGaming** [comment]
HTML5 was marked depreciated in 4.23, and will no longer be available in later engines. It will become a community add-on via github
https://github.com/UnrealEngineHTML5/UnrealEngine/tree/4.24-html5/Engine/Platforms/HTML5

**Comment by EvoPulseGaming** [comment]
Also note in 4.24 there is this patch note:
Bug Fix: HTML5 is blacklisted on ApexDestruction, as APEX does not build for HTML5.

You will have to remove the destructible buoyant actor from c++ code
