### ISSUE TITLE
When compiling with UE4.25 UActorComponent::bIsActive is inaccessible.

### ISSUE THREAD

**Issue by sysopj** [UE4-OceanProject/OceanProject#134]
My workaround was to comment out the "bIsActive ||" section that gave me issues.

**Comment by script526** [comment]
The workaround is to replace this variable with a getter function IsActive() and you would know it if you read the faq section of the Discord channel.

**Comment by EvoPulseGaming** [comment]
^I thought about commenting the same message. Made me smile to see this.

**Comment by script526** [comment]
Why is that even an issue if you have replaced the bIsActive with IsActive() already? Maybe the guy is using an older version or something, Or he might be downloaded it earlier, before the '4.25' commits and encountered the issue just now.
