### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by ahmetArdaErdogan2007** [UE4-OceanProject/OceanProject#137]
I can't open the project on 4.25
![15952786336156750248703136783327](https://user-images.githubusercontent.com/67742369/87985846-92a31a80-cadc-11ea-9aae-10bf7a11e9f2.jpg)
![15952787405995727794875790617765](https://user-images.githubusercontent.com/67742369/87985904-ab133500-cadc-11ea-88f4-6a97c769244b.jpg)

**Comment by archsolar** [comment]
Did you download the zip? 

Copied from the discord group:
If you download the repo as a zip you must run this command in git (bash) in the ROOT folder of the project :
git submodule update --init --recursive
Or just use github/smartgit to download, as it will pull the submodules (plugins) required.(edited)

**Comment by EvoPulseGaming** [comment]
Closing as all information needed is on the discord, which is linked to in the readme.
