### ISSUE TITLE
Some strange wavebreak on ocean surface

### ISSUE THREAD

**Issue by flashASA** [UE4-OceanProject/OceanProject#139]
See some strange wavebreak on ocean surface

https://drive.google.com/file/d/1JJ2jMGuuWfsTidGVHgy3pN6OSts8a0rL/view?usp=sharing

**Comment by EvoPulseGaming** [comment]
I'll add it to my todo list

**Comment by EvoPulseGaming** [comment]
Appears fixed on my end using latest.
