### ISSUE TITLE
ERROR: Missing precompiled manifest for 'OceanPlugin'

### ISSUE THREAD

**Issue by kapasifulop** [UE4-OceanProject/OceanProject#140]
Hi!
When i try to package my project, with '**OceanPlugin**' and this project Ocean folder **(OceanProject-MASTER_LEGACY_FINAL_4.25\Content\Ocean)** then I get this error code:

```
UATHelper: Packaging (Windows (64-bit)):   ERROR: Missing precompiled manifest for 'OceanPlugin'. This module was most likely not flagged for being included in a precompiled build - set 'PrecompileForTargets = PrecompileTargetsType.Any;' in OceanPlugin.build.cs to override.
PackagingResults: Error: Missing precompiled manifest for 'OceanPlugin'. This module was most likely not flagged for being included in a precompiled build - set 'PrecompileForTargets = Preco
mpileTargetsType.Any;' in OceanPlugin.build.cs to override.
```

![image](https://user-images.githubusercontent.com/69323434/96740808-78b9f200-13c1-11eb-836c-9998d00720c7.png)

**Comment by NightMare489** [comment]
Move the plugin from Engine's Plugins folder to Project's Plugins folder (if you don't have one just create a new folder name it "Plugins")
![image](https://user-images.githubusercontent.com/56297925/96789906-3f4fa980-13f6-11eb-8382-70d9660ed228.png)

Also you may encounter another issue while packaging in 4.25 :
`
/Plugins/OceanPlugin/Source/OceanPlugin/Private/OceanManager.cpp(116): error C2440: 'static_cast': cannot convert from 'ElementType *' to 'FColor *'
`

if you encountered this then go to "Plugins/OceanPlugin/Source/OceanPlugin/Private/OceanManager.cpp" at line 116, change "static_cast" to "reinterpret_cast"
