### ISSUE TITLE
Wave buoyancy mesh doesn't align in certain places

### ISSUE THREAD

**Issue by Waffle1434** [UE4-OceanProject/OceanProject#17]
Severe wave misalignment when generating large waves (>5m) in certain areas (usually worst at 0,0). In other places mesh appears to be aligned and works well. Buoyant objects appear to be riding an invisible wave that doesn't match the visible wave.

**Comment by dotcamdev** [comment]
Sorry for such a delay in response here, I thought I had notifications turned on... :/

Is this still occurring in your project? If so could you please let me now what kind of setup you have for the object? If the object does not have Physics enabled it will use an alternate buoyancy method that doesn't actually simulate it, instead just moves it up and down, and could be off by a large amount if it is set up a certain way.

If possible please take a screenshot showing the Buoyancy settings also, this will help us narrow down the issue.

Thanks
