### ISSUE TITLE
Package failure

### ISSUE THREAD

**Issue by Mat5i6** [UE4-OceanProject/OceanProject#18]
Clean version of your project is unable to be packaged correctly (tried 4.10 - 4.12)

Program.Main: AutomationTool exiting with ExitCode=5

**Comment by Nsomnia** [comment]
Administrative issues. Run vs as an admin and check your code compiles before linking.

**Comment by Mat5i6** [comment]
Doesn't work. I'm able to package new blank project but even with admin rights it returns same error

Edit: Ok, maybe I've found solution but I need to test it first. I'll post results. Thanks for help.

**Comment by Mat5i6** [comment]
Problem was with unreal and its unability of finding files with latin characters in file path so thanks for help :)

**Comment by Nsomnia** [comment]
Thjat'll do it. Code 5 is always something stupid.
