### ISSUE TITLE
Optimalization

### ISSUE THREAD

**Issue by Mat5i6** [UE4-OceanProject/OceanProject#19]
Hi! Again me and I need to ask about optimalization. As I tested having ocean in level and it drops my FPS from stable 60 to 20 - 10 and I have one of best gaming computers available so probably I did something wrong with setup. So if there are some variables that should stay on low values or something, because even with ocean old or others doesn't help so much. 

![with](https://cloud.githubusercontent.com/assets/20024981/17343766/a975271a-58ff-11e6-8e5c-ca29e2021928.png)
![withouth](https://cloud.githubusercontent.com/assets/20024981/17343767/a975878c-58ff-11e6-947a-758404e31035.png)

Also I want to ask if I can donate you somewere because this awersome work that you did shouldn't be left without notice and reward :).

**Comment by dogsofknowledge** [comment]
Turn off planar reflections, see if that helps.

**Comment by Mat5i6** [comment]
Not so much still getting over 30 FPS is an achievement but visually it's now really bad

**Comment by dogsofknowledge** [comment]
If it's not possible to use SSR instead, then I guess you need to create a new level and try it there. Also make sure you are using the Ultra version.

**Comment by Mat5i6** [comment]
Well not much of a change, after creating new world I just placed ocean, light, etc. with default settings and just to try I send packaged version of it to my friend which can run GTA 5 on highest settings (not much of a big deal now but just to compare it) and he had cca 40 FPS, nothing just ocean and lightning so I wonder what causes so much FPS drain? I know that you already pointed that planar reflections are expensive but still it's too much. Can be there something else that can be turned off or maybe setted up wrongly?

**Comment by dogsofknowledge** [comment]
No, I don't think there's anything else. What graphics card do you have?

**Comment by Mat5i6** [comment]
GeForce GTX 980

**Comment by Mat5i6** [comment]
I will probably try to download original ocean project and see if there I will have also FPS problems if yes than I don't know what to do else if no I bothered you here 3 days with my stupidity and I'm sorry for that.

**Comment by dogsofknowledge** [comment]
I have that card too and get over 80-100 FPS. What about your CPU?

**Comment by Mat5i6** [comment]
Intel Core i7-6820HK 2,7GHz

**Comment by dogsofknowledge** [comment]
There's your problem. The processor is probably bottlenecking the GPU, either overclock it to at least 4GHz or replace it with another processor.

**Comment by dogsofknowledge** [comment]
I have a GTX 980 and an I5 - 4690k at 4.7 GHz, the ocean project always runs at 120FPS with planar reflections on.

**Comment by Mat5i6** [comment]
that's factory speed, while using unreal engine editor it jumps to 3,92 - 4,2 because of overclocking

**Comment by Mat5i6** [comment]
OK... I have no idea what I did in my current project that made it so laggy but my FPS in original is 60 (frame limit enabled). So I want you thank you for help and I want to apologize for your time that you wasted because of me. Thanks.

**Comment by dogsofknowledge** [comment]
Glad to hear it's working, I don't know of anything that you could have done to make it so slow.

**Comment by worisinima** [comment]
Hello，As far as I can see，you can turn moveable light to statiandmoveable light。and then build light。you can also reduce the number of physical actors。In this way，FPS may increase。
