### ISSUE TITLE
Strange underwater material problem！！！

### ISSUE THREAD

**Issue by worisinima** [UE4-OceanProject/OceanProject#20]
This is a strange problem。In my project, All the setting of the M_underwaterPP is same to origin project downloaded from githug。But in my project，there is no use when I drag this material instance to globlePostprocessVolume。However，it works well in downloaded project。I really need help！why The underwater material instance can't work ？I have drag Bp-underwater in to my level and finished all the settings。I am sure that this problem is due to underwater material 。but I don’t know how to solve this
problem。I really need help！

**Comment by worisinima** [comment]
Is there anybody can tell me that the Working principle of this material？

**Comment by Nsomnia** [comment]
Go to the forum thread. You need to create an underwater PP volume set the M_Underwater_inst turn it off and then use logic to check if the camera is underwater and set it to on if so. Check hte default maps for how they call OceanManager.GetWaveHeightValue() to acheive this based on GetPlayerCameraManager()->GetWorldLocation()

**Comment by worisinima** [comment]
thank you so much! I‘ve solved this problem successfully。
