### ISSUE TITLE
Problems (And Fixes!) For UE4 4.13 

### ISSUE THREAD

**Issue by cascade256** [UE4-OceanProject/OceanProject#21]
I just updated my project to UE4 4.13 and tried to recompile the ocean plugin, but there were some compile errors. I managed to fix them by matching the deprecated variables to what I think are the new correct functions. I made a branch in my fork with all the changes in it, and would be more than happy to submit a pull request if a new branch could be opened up for 4.13.

Thank you for sharing this great project!

**Comment by flashfreak** [comment]
Would LOVE to get a copy of that!  My project pretty much required 4.13, and I also want to continue using this plugin.

**Comment by cascade256** [comment]
No problem! I uploaded it to my fork under a 4.13 branch. Here is a link: [https://github.com/cascade256/OceanProject/tree/4.13](https://github.com/cascade256/OceanProject/tree/4.13)

Let me know if you have any issues getting it set up.

**Comment by flashfreak** [comment]
​I nabbed it, thanks! It's working just fine.

Perfect timing, I was wondering when/if a 4.13 branch would release.

**Comment by kpd200081** [comment]
You do really great work!

**Comment by TheZoc** [comment]
Apparently, 4.12 is the "master" just because it's the latest.
Submit a PR, they will create branches and rename the as necessary :)

Edit: You probably want to "squash" everything prior submitting a PR ;)

**Comment by bmcgauley** [comment]
was mandatory for me to upgrade for a few things as well, also for our project it was mandatory to have this plugin to save time.  going to try right now to see if this works, thanks for taking the time to update it I was in full on panic mode!

**Comment by bmcgauley** [comment]
it worked, thanks so much for your update!

**Comment by TheZoc** [comment]
@bmcgauley Glad it worked for you!

There are a few more fixes here in case you need them: https://github.com/TheZoc/OceanProject :)

**Comment by bmcgauley** [comment]
Thanks, Ill integrate for our next update! :)

**Comment by cascade256** [comment]
Hey everyone! Sorry for not responding to your comments, college has been pulling me away from working on open source projects.

It looks like @TheZoc has taken on updating it to 4.14, so I think his fork will be the one to use going forward. I am glad mine was able to help a few people in the meantime. 

@MrPavel3243 Thanks!
@bmcgauley No problem!

**Comment by worisinima** [comment]
虚幻4的4.13版本有很多bug。物理引擎好像还有有很多问题就发布了。比如CableComponent在游戏打包之后会失效。建议不要使用4.13这个版本，引擎很不稳定而且bug很多。

**Comment by worisinima** [comment]
虚幻4的4.13版本有很多bug。物理引擎好像还有有很多问题就发布了。比如CableComponent在游戏打包之后会失效。建议不要使用4.13这个版本，引擎很不稳定而且bug很多。

**Comment by worisinima** [comment]
By the way，顺便问一下。这个demo还有一些不足，那就是人物在水面上游动的时候无法和海洋水体产生波纹，我做了一些尝试，但是效果都不是特别理想。我做的效果看起来很假。请问作者您有一些做这种波浪的思路吗？谢谢！
