### ISSUE TITLE
Ocean materials are invisible

### ISSUE THREAD

**Issue by MrGparter** [UE4-OceanProject/OceanProject#22]
When I load up the project on 4.12/4.11 (only ones I have tested) the materials for the ocean are invisible, the textures assigned to the materials are visible but the materials are not.

I'm currently on a fresh install of unreal engine so I don't think that is the problem.

my specs are:
r9 280x oc
fx 6350
8 gb 1600ddr3 ram
2x2 tb hdd 7200 rpm
### Thank you.

![bug](https://cloud.githubusercontent.com/assets/6211196/18538994/6c2e4a04-7ac8-11e6-9255-0cb5feb396bd.PNG)

**Comment by mciccarone** [comment]
This might be a stupid question, but did your shaders finish compiling?

 I vaguely remember having to play in editor the first time I ran the Ocean Project plugin to get the ocean mesh to appear. What happens if you turn on Simulation (Alt+S) ?

**Comment by MrGparter** [comment]
Thank you for your reply.

Yes, all of my shaders are finished compiling, I have even tried removing and replacing a few nodes of the materials in order to make sure each one has compiled. When I turn on Simulation the result is the exact same.

**Comment by MrGparter** [comment]
Problem solved upon switching to shader module 4.

Thank you for your hard work and dedication to this great plugin.

**Comment by MrGparter** [comment]
Issue solved by upgrading from win 8.1 to win 10 and reinstalling graphics drivers.

Thank you for your hard work and dedication to this project.
