### ISSUE TITLE
Compatibility with Unreal 4.14 

### ISSUE THREAD

**Issue by Bmahoneyff7** [UE4-OceanProject/OceanProject#28]
Thank you so much for this water shader, it looks fantastic. I have a question though, due to baking lighting issues I was having in 4.12 I tried moving my project to Unreal 4.14 and it seems as though the water blueprint doesn't load, it's just blank. Is this technically possible to get running in UE 4.14? Thanks again!

**Comment by neico** [comment]
see #25 and #26
