### ISSUE TITLE
with clang error: implicit conversion of NULL constant to 'float'

### ISSUE THREAD

**Issue by mariuz** [UE4-OceanProject/OceanProject#3]
Plugins/OceanPlugin/Source/OceanPlugin/Classes/Fish/FlockFish.h(139,25) :  

error: implicit conversion of NULL constant to 'float' [-Werror,-Wnull-conversion]
    float CustomZSeekMin = NULL;

**Comment by ericwomer** [comment]
Change that NULL to 0.0 and see if it helps.
