### ISSUE TITLE
matinee problem

### ISSUE THREAD

**Issue by MedWajih37** [UE4-OceanProject/OceanProject#30]
whatever matinee i make in the end a video with text ( like camera falling from the sky straight to the water that i didn't make it) is exported in the desktop

**Comment by victor-vexargames** [comment]
I have no idea what you are talking about. I have the water working in 7 cinematics in 4.15 using the sequencer. I never go under the water. You might want to edit your comment to be more descriptive.

**Comment by MedWajih37** [comment]
Hello Victor,
when i film my matinee and press capture movie always this video appears in
the desktop whatever the matinee that i record. like this exactly :


​

PS : Thank you for sharing the project it was an incredible work from you
and i wish you all the success in the future my friend  please help me
solving this problem .
kind regards,



[image: photo]
*Med Wajih Souilem*
Electronics Engineer
Medwajihsouilem37@gmail.com | Skype: Wajih.souilem37 <#>
<http://www.facebook.com/medwajih.souilem>
<http://www.linkedin.com/in/med-wajih-souilem-b56101113?trk=nav_responsive_tab_profile>
  <http://twitter.com/>  <http://plus.google.com/u/0/116922088654298320802>
Get a signature like this: Click here!
<http://ws-promos.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS9lbWFpbC1pbnN0YWxsP3dzX25jaWQ9NjcyMjk0MDA4JnV0bV9zb3VyY2U9ZXh0ZW5zaW9uJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NhbXBhaWduPXByb21vXzU3MzI1Njg1NDg3Njk3OTIiLCAiZSI6ICI1NzMyNTY4NTQ4NzY5NzkyIn0=&u=873085002241636>
ᐧ
