### ISSUE TITLE
Update plugin to 4.15

### ISSUE THREAD

**Issue by StartOrigin** [UE4-OceanProject/OceanProject#31]
Please someone could update the plugin to version 4.15

(Or try to provide some version with necessary complements ) please

**Comment by victor-vexargames** [comment]
Zoc's version runs on 4.15

**Comment by magnusroe** [comment]
It fails to convert the files to 4.15 on both my computers. Perhaps someone could upload their converted archive?

**Comment by victor-vexargames** [comment]
Do you have visual studio installed? Are you trying to compile it on its own? I would but I removed all the content that I didn't want in the project so it is a striped down version of the project at this point.

**Comment by magnusroe** [comment]
I have VS 2015 installed, I'm not doing anything but try to open the project in 4.15 and it says it needs to convert some files, which it fails to do. The project is then labeled 4.15, but won't open.

**Comment by victor-vexargames** [comment]
I already installed the plugin on the 4.14 version. Then converted the project from 4.14 to 4.15 using the Launcher.

I already had it working in 4.14, then recompiled it 4.15. Actually for this particular project it was started with 4.7, and I have upgraded it a few times up until Zoc had to make some changes for it work in 4.14. 

I might be able to help you on stream, I stream UE4 dev on twitch.tv/vexartv might be faster. I can at least show you how I have it setup. Like I said I customized my version by removing all content that wasn't required for my project by doing this I might have fixed something that is causing your troubles. I am remove the variable elements type guy to reduce the complexity of the problem.

I will fire up the stream in a few minutes of this message, so swing by and I will try to show you what I have. Let me know you are in the chat.

**Comment by magnusroe** [comment]
I just managed to convert it with a third computer, guess my VS install has a bug on the other rigs.
Still no luck migrating it between projects though, which makes it a bit clunky to use with current projects :(

**Comment by StartOrigin** [comment]
@victor-vexargames  Is it possible for us to have your 4.15 ocean project content without the unnecessary content of ocean project?

**Comment by victor-vexargames** [comment]
No sorry because it is not mine it is Zoc's modified version, just download his version pull request it does work with 4.15. I am not an engineer or programmer.
