### ISSUE TITLE
4.15 compatibility issue

### ISSUE THREAD

**Issue by AngelOfDeath1000** [UE4-OceanProject/OceanProject#33]
Been trying to get this working on 4.15 with no luck, I can only get it running in 4.14.3, I'm using Zocs branch/build/thing...

When I open it in 4.14 and go to compile I get and Error Windows sdk v8.1 needed, I'm using Win10 and I've got VS 2015 installed.

When I go to convert the 4.14 project to 4.15 I get Project Files could not be generated ... followed by 
"The following modules are missing or build with different engine version: 
UE4Editor-OceanProject.dll
UE4Editor-OceanPlugin.dll
Would you like to rebuild them now

After clicking yes I get Starting build and then OceanProject could not be compiled, Try rebuilding from source manually.

When I try to open the project that has the plugin in it I get "Missing or incompatible modules, would you like to disable. Both yes and no lead to UE4 crashing/not opening the project.

Any help would be appreciated, thanks

**Comment by mrG7** [comment]
You need to get Windows SDK v8.1 , just download it. 

Are you using the source or build versions of the engine?
