### ISSUE TITLE
[4.15 Bug] engine seems to crash after installation

### ISSUE THREAD

**Issue by johnfg2610** [UE4-OceanProject/OceanProject#36]
seems like the engine is unable to launch after installing the shaders

**Comment by tk-master** [comment]
I had a readme in the shaders folder stating "Use these only with the engine version the branch is marked for.
The engine will crash if used with an incompatible version so I recommend you to BACKUP the original files first."

But it seems it got removed..

Anyways, I will see if I can find some time to update them for 4.15 but just know that these will always cause a crash with a new engine version.
