### ISSUE TITLE
[SOLVED]Update 4.16

### ISSUE THREAD

**Issue by OAXP** [UE4-OceanProject/OceanProject#37]
Hey please update for 4.16 :D

**Comment by victor-vexargames** [comment]
It already works on 4.16 I didn't even need to recompile just converted the working 4.15 project to 4.16. Stop being lazy. :-)

**Comment by OAXP** [comment]
What about the plugin ?

**Comment by victor-vexargames** [comment]
It is working, see the box in the middle it has the version number of the engine I am using.
http://imgur.com/Uradw2i

**Comment by OAXP** [comment]
Ok thanks :D

**Comment by victor-vexargames** [comment]
No problem, if you have troubles let me know. One thing you can try is zoc's branch or remove all assets that are not needed in your project.

**Comment by ghost** [comment]
I have some problems when importing the ocean could tell me the correct method or that you used, I would like to import only important materials

**Comment by victor-vexargames** [comment]
If I was starting right now I would download Zoc's branch which has some good fixes, and install the entire thing with out trying to take items out of it. 

Once you learn how it all works you can remove the content you do not want. 

The examples they provide are good for learning. I only removed them after I did this process. The other thing about this method is that you will have confidence that you have something that has worked for someone else.

**Comment by Messia91** [comment]
Does not work the ocean on version 4.16 please fill in the ocean

**Comment by Messia91** [comment]
![image](https://user-images.githubusercontent.com/17235149/26867692-698b5848-4b77-11e7-980a-bf3c77e9960b.png)

**Comment by JanonymusR** [comment]
I am new to UE4
Could you please make some detailed instructions on how to use this in 4.16.1?

**Comment by TheZoc** [comment]
The current version of the project supports Unreal Engine 4.17!

If you need 4.16 support, you can check the commit b13624f - it works nicely here (even though it says it needs 4.15, you can safely open/recompile it for 4.16, it's fully compatible!)

From now on, I'll try my best to have an updated branch for each version :)
