### ISSUE TITLE
How Do I add this to an existing Project?

### ISSUE THREAD

**Issue by anUrbanGoose** [UE4-OceanProject/OceanProject#38]
I am very new to Unreal, and I don't know how to use this with an existing project.
I also don't know how to update this to a new engine version.
( I read something about recompiling in [this thread](https://github.com/UE4-OceanProject/OceanProject/issues/37), but I don't know where / how to do this.

I'd love it, if somebody could write some instructions!

**Comment by worisinima** [comment]
Firstly,you need copy the plugin folder into your project and you need also copy all the uassets into your project.Then you need Open the VS and compile this project,setting up a debug instance.Finally,opening the plugin manager,active this plugin.

**Comment by anUrbanGoose** [comment]
Thanks, but I cant get it to work with 4.16.1

**Comment by worisinima** [comment]
So？ You can get it to work with 4.16.1 and Does it have anything to do with your question？I really can't understand your western logic.

**Comment by anUrbanGoose** [comment]
You're right, I should have opened a new thread for this. It works with 4.15, but not with 4.16.1

**Comment by worisinima** [comment]
Maybe there is another way to deal with it。Firstly setting up a new project with unreal engine 4.16.1 and then setting up a plugin folder in your project。Copying the OceanPlugin into plugin folder of your new project。After above steps，you need also copy the UAssets of the OceanProject into your new project ，that 4.16.1 project。Finally，opening the VS and regenerate the project，Reloading all items。Then you need recompile your new project。At this time，Some error maybe come out，you need correct them。After all these thing，The editor will be open！

**Comment by Imperius122986** [comment]
So do I have to install Unreal Engine 4.15 to use 4.16? I don't have a pre-existing project to rebuild this.

**Comment by Imperius122986** [comment]
Well I installed 4.15, and it wouldn't run something about can't access a folder in my user local. I assume this is because 4.16 uses it. 

Anyway I cant test this out sadly. I will be watching for an update.

**Comment by anUrbanGoose** [comment]
I have the same issue as Imperius122986, so I guess I'll just have to wait

**Comment by TheZoc** [comment]
@JanonymusR and @Imperius122986 

were you able to solve your issue? :)
