### ISSUE TITLE
UE4 Newbie needs help updating to 4.16.1

### ISSUE THREAD

**Issue by anUrbanGoose** [UE4-OceanProject/OceanProject#39]
Like the title says, I am quite new to UE4 and I couldn't find any useful guide to updating this to the new engine version.

**Comment by Luminatrixx** [comment]
Hello JanonymusR,
- First you have to set up a new project in 4.15 with the plugin integrated (It have to be a C++ project or just a blueprint project with a C++ class added in).

When it's done, you will open your new project with 4.16.1 and Unreal Engine will try to automatically convert the project to newer version. 

![helpopencopy](https://user-images.githubusercontent.com/26882196/27953943-04ef3810-630e-11e7-92c0-ef89902cde55.png)

- Then, when it's finish, generate VS project files by right-clicking on your new project file (i.e oceanplugintest.uproject) and selecting" Generate Visual Studio Files". 

![help](https://user-images.githubusercontent.com/26882196/27953846-a495db7c-630d-11e7-8261-54708cbd8d4f.png)

- After that, open the .sln file in Visual Studio and select "Build" => "Generate Solution". Be sure to select Target Plateform = Win32 or Win64 (depend on what you need) and configuration : Development_Editor (To be able to use it in Editor).

![helpdev](https://user-images.githubusercontent.com/26882196/27954114-d18ca010-630e-11e7-9f59-4ed168fa8d9c.png)

- Now it's done, you can use the plugin with 4.16.1 version.

Hope that help.

Younes

**Comment by anUrbanGoose** [comment]
Still not working, the Ocean shows up as a bad Blueprint...
Guess I just have to wait for a new version by the devs

**Comment by johnfg2610** [comment]
https://github.com/johnfg10/OceanProject/tree/4.16 try that :)

**Comment by anUrbanGoose** [comment]
@johnfg10 Thank you SOOOO much! It finally works!!
