### ISSUE TITLE
Landscape overtakes sea when looking from high above / distance

### ISSUE THREAD

**Issue by shaisa** [UE4-OceanProject/OceanProject#41]
Using 4.16.2.
Implemented the ocean and ended up with quite a good result. However, the landscape seems to make the sea disappear when viewing from high altitude / far.
Low altitude / close range:
![image](https://user-images.githubusercontent.com/24991662/28836459-aa8cfe32-76f1-11e7-9139-a1e18ffad3c8.png)
High altitude / long distance:
![image](https://user-images.githubusercontent.com/24991662/28836477-bdd28dea-76f1-11e7-9e53-8405bb0df5f1.png)

It happens at around 3,000 meters from the sea surface (upwards or sideways).
I checked in the OceanProject and it happens there too around 10,000 meters.

Do you have any idea what's the cause? Is it landscape or ocean settings?
Is there a way to fix this issues?

**Comment by TheZoc** [comment]
Hello @shaisa :)

Do you still have this issue?

If you have, have you tried copying the blueprint from the map that works to your map and see if this fixes the issue?
I want to know if the issue is related to the blueprint itself or some other level setting.

Thanks in advance!

**Comment by shaisa** [comment]
I eventually solved it by applying visibility mask to the landscape and mask out the parts of the landscape that is overlapping with the Ocean.
So,I haven't tried copying the BP from the other project. Maybe I'll give it a try in the future.

I'll mark as resolved since I think it's an engine "feature" rather than a Ocean_BP bug.

Thanks for the help :)
