### ISSUE TITLE
No Eclipse

### ISSUE THREAD

**Issue by nzavagli** [UE4-OceanProject/OceanProject#44]
I was playing with the project and the high accuracy sky. I noticed that the moon does NOT intersect path of the sun when the date is set to Aug 21 2017, and the lat/long coordinates are set to be in the path of totality for the real eclipse.

While I can play with blueprints to get the moon and sun to cross paths (basically just use the sun rotation function for updating the moon - a cheat, but it worked), the moon invariably ends up passing behind the sun, rather than occluding it from in front. 

Any help/ideas would be appreciated.

**Comment by TheZoc** [comment]
Hello @nzavagli :)

Were you able to fix your issue? :)

**Comment by EvoPulseGaming** [comment]
Why was this closed? Elcipses are still broken, I even used actual meshes for the sun and moon so this is not a skydome issue. I've written a post on the forum describing the setup for the eclipse using the same date and time for Aug 21, 2017

**Comment by TheZoc** [comment]
@saschaelble can you link to the post and/or submit a fix as a pull request? :)

**Comment by EvoPulseGaming** [comment]
I do not have a fix for this, I was just showing this is a reproducible issue.
https://forums.unrealengine.com/community/work-in-progress/17331-community-project-wip-weather-ocean-water-shader?p=1416555#post1416555

**Comment by dotcamdev** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [BUG: No Eclipse](https://trello.com/c/tMAS5W6g/60-bug-no-eclipse)

**Comment by EvoPulseGaming** [comment]
Update: I've fixed the issue with the moon showing up behind the sun, after I am sure the moon position is correct, I will close this and merge my test branch into master

**Comment by EvoPulseGaming** [comment]
for now, check out the diftow branch
