### ISSUE TITLE
how do i  check collision  to ocean surface? 

### ISSUE THREAD

**Issue by BHSUnreal** [UE4-OceanProject/OceanProject#47]
hello ?
i have some question about collision with ocean surface.
i want a water splash for  gun fire and something.
Would you let me know this?
thanks!!

PS) there is a crash bug when change viewport to Top view ;)

**Comment by TheZoc** [comment]
@BHSUnreal Are you able to reproduce the steps to crash the editor? :)

About having particles when hitting the ocean, this should be a weapon collision check, probably by using a physics material 🙂
