### ISSUE TITLE
CompileFailure4.18

### ISSUE THREAD

**Issue by ZORN8496** [UE4-OceanProject/OceanProject#48]
Compile Failure using ue4 4.18

1>    Running UnrealHeaderTool "F:\UnrealProjects\OceanProject\OceanProject\OceanProject.uproject" "F:\UnrealProjects\OceanProject\OceanProject\Intermediate\Build\Win64\OceanProjectEditor\Development\OceanProjectEditor.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors -installed

1>EXEC : error : Couldn't find parent type for 'BuoyantDestructibleComponent' named 'UDestructibleComponent' in current module or any other module parsed so far.

1>EXEC : error : UnrealHeaderTool failed for target 'OceanProjectEditor' (platform: Win64, module info: F:\UnrealProjects\OceanProject\OceanProject\Intermediate\Build\Win64\OceanProjectEditor\Development\OceanProjectEditor.uhtmanifest, exit code: OtherCompilationError (5)).

1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.MakeFile.Targets(41,5): error MSB3075: The command "F:\UnrealEngine\UE_4.18\Engine\Build\BatchFiles\Build.bat OceanProjectEditor Win64 Development "F:\UnrealProjects\OceanProject\OceanProject\OceanProject.uproject" -waitmutex" exited with code 5. Please verify that you have sufficient rights to run this command.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by TheZoc** [comment]
Fixed in f67e716
