### ISSUE TITLE
Wakes missing on UT 4.17 and 4.18

### ISSUE THREAD

**Issue by ineteye** [UE4-OceanProject/OceanProject#50]
Hi! Tested new Oceanproject for UT 4.17 and 4.18 and find problem that Wakes that generates after boats does not works fine((( 

I think it cause modification of water... earlier in 4.15 Harpoon stucks in waves, sometimes... now it does not happens) but wakes works not fine(( And looks it somehow goes over lifespan time .... bp_wakes... just destroying afrer creation.... Any help???? That all heppens on main Island map!

**Comment by tshao4** [comment]
Might be the same issue as #51 
Setting <BP_Wake - SM_SplinePlaneMesh - Details - Rendering - Translucency Sort Priority> to 1 gets the wakes to show up. Losing depth test on the wakes may not be a huge deal(?)

**Comment by ineteye** [comment]
TY)) That works)) Hope you resolve that problem in future updates)))
