### ISSUE TITLE
Transparency issue

### ISSUE THREAD

**Issue by AnneWellings** [UE4-OceanProject/OceanProject#51]
Any transparent material that I look at in front of the ocean is getting masked by it. 

![image](https://user-images.githubusercontent.com/11259812/32299697-2584f988-bf1c-11e7-8fde-edde0c0730e6.png)

**Comment by tshao4** [comment]
A temporary workaround: you can set <YourStaticMesh - Details - Rendering - Translucency Sort Priority> to 1, but then you lose depth test I guess.

**Comment by AnneWellings** [comment]
Alright, thanks :)

**Comment by victor-vexargames** [comment]
This is happening with emitters and transparent objects has been like this the first version of 4.17. Someone posted a fix on the Unreal 4 forums you might want to try it or hope Zoc fixes it.

**Comment by TheZoc** [comment]
@victor-vexargames can you send me that link, please? :)

**Comment by dotcamdev** [comment]
Closing this issue as it is a duplicate, there is more info in the other issue discussion. Please use issue #53 for further discussion

https://github.com/UE4-OceanProject/OceanProject/issues/53

**Comment by dotcamdev** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Transparent Object Issue with Ocean in Level](https://trello.com/c/Ws55P2UZ/65-transparent-object-issue-with-ocean-in-level)
