### ISSUE TITLE
Skeletal Mesh!

### ISSUE THREAD

**Issue by ineteye** [UE4-OceanProject/OceanProject#54]
Hi!

See that skeletal mesh support, but did not find any mentions about that)
Just put skeletal mesh under Static mesh or there other way?
Cause all boats and ships is static mesh and component PawnCollisionMesh works only with StaticMesh(

**Comment by ineteye** [comment]
I got what is PawnCollisionMesh - just a static mesh... i create same as skeletal.... but now have to understand how to stop moving all skeletal mesh parts in water)

**Comment by ineteye** [comment]
That was just collition problem... But in result... Skeletal model is going down... and looks BuoyancyForce does not effects (((
Looks something should change in Constraction script???

**Comment by ineteye** [comment]
And Looks get finaly with collition)))

**Comment by TheZoc** [comment]
Hello @ineteye!

Can you explain more of what issue you had and how to fix it? I'd love to have a working example in the repository.

Thanks in advance!

**Comment by ineteye** [comment]
I  did not complete it yet .. )) But i was making boat with skeleton... also it good for animals)) Hmmm... have to check how fish was in work... sketal character or not)

**Comment by TheZoc** [comment]
@ineteye I see that you removed your PR regarding this issue. Was anything wrong?

I apologize for being late on this PR, I didn't have time to review it earlier, sorry!

**Comment by dotcamdev** [comment]
Will look into this asap

**Comment by EvoPulseGaming** [comment]
This is not within the scope of the project.
