### ISSUE TITLE
Waves are jumpy

### ISSUE THREAD

**Issue by speedpacer** [UE4-OceanProject/OceanProject#57]
Just cloned and compiled 4.18 and the latest Ocean plugin and in the IslandMap example, the waves are jumpy as the character is moving.  It's like new animations are starting before the old ones finish or something, if that makes sense.  Is anyone else experiencing this?  If not, I'll try to post a video.

**Comment by magnusroe** [comment]
I also have this, I think I had it since 4.17.
The ocean example 1 and 2 maps are normal though.

**Comment by TheZoc** [comment]
I don't remember seeing that issue, but it's definitely possible.

Are you able to pinpoint in what version did it change its behavior? There were some internal changes as how UE4 handles some of the needed math functions, and it could be something pretty obvious or something as hard as finding a needle in a haystack...

Thanks!

**Comment by speedpacer** [comment]
I didn't notice it with my forked repo (https://github.com/speedpacer/OceanProject 4.16-to-4.17 branch) that I had tinkered with to get it to work with 4.17.  I think I still have that project. I'll verify when I get home.

Thanks magnusroe: I haven't tried the other maps.  I'll go ahead and migrate it to my project and see if it goes away.

**Comment by speedpacer** [comment]
Okay, it was happening in the 4.17.2 installed with the launcher but not as badly.  It wasn't happening from a compiled 4.17.1 after being migrated to another project.  Haven't tried migrating to 4.18 project yet.

**Comment by speedpacer** [comment]
Finally got a chance to migrate this into a 4.18.2 project installed from source and it's still happening unfortunately.

**Comment by TheZoc** [comment]
@speedpacer Were you able to pinpoint the change that caused this ?

There were a few changes when upgrading to 4.17 (as you can see in 0913588958134a6ca4230e37ceac1a83bfefd719 ), but there weren't many changes upgrading to 4.18 (f67e716f4a76f1cb15ba7547937be8bd85d712dc). Many changes happened in 4.15 upgrade (e51e52bb75af1be09cbf019e624e103ae7f66b6e - if you're going to check this deeply, please note there are other commits done to the 4.15 version!), but I can't find anything that sounds like the cause of this issues.

Thanks again! :)

**Comment by speedpacer** [comment]
@TheZoc I haven't been able to pinpoint this unfortunately.  I sorta chalked it up as something I could live with for now and pressed on. 

Are you still not able to see this?  The more I think about it, I also changed computers around the same time I started experiencing this, from an AMD 8350 with a GTX 770 to an i7 with a GTX 1060.  I believe there was also a Win7 to 10 update involved with that as well. If some are experiencing this and others aren't, maybe it's something other than the UE version.

**Comment by dotcamdev** [comment]
I'm 99% sure this issue was related to the Infinite System conflicting with another setting, but I can't seem to reproduce it in the latest build. 

If there are still issues after upgrading to the upcoming update please reopen this issue and let us know. Thanks!
