### ISSUE TITLE
add torque was Abandoned

### ISSUE THREAD

**Issue by cqh963852** [UE4-OceanProject/OceanProject#65]
![image](https://user-images.githubusercontent.com/17702287/36092059-ff878f38-1020-11e8-86f4-df6651833400.png)

In BP_ManOfWar
UE 4.18.3

**Comment by TheZoc** [comment]
Did you improve this blueprint? If so, can you send a pull request? :)

**Comment by cqh963852** [comment]
sorry for that,I‘m new to github,But you are right,I'll try to improve this BP.

**Comment by TheZoc** [comment]
@TheBegining Any updates on this? :)

**Comment by cqh963852** [comment]
![image](https://user-images.githubusercontent.com/17702287/37864870-6427e282-2faf-11e8-9a6c-7bf0ed8496a2.png)
I'm going to use Add Torque in Radians in BP_ManOfWar,but i don't know if it is right.

**Comment by dotcamdev** [comment]
This issue has been fixed in PR #79 that has been pushed to master just now.
