### ISSUE TITLE
Ocean Plugin in 4.17 compiled for 4.18

### ISSUE THREAD

**Issue by popeyesfx** [UE4-OceanProject/OceanProject#67]
The Ocean Plugin on the 4.17 branch (the highest I can use), says its not compatible with 4.17.2, as its for version 4.18.

Do you have a 4.17 version

**Comment by TheZoc** [comment]
Hello @popeyesfx ,

Looking at the [project file](https://github.com/UE4-OceanProject/OceanProject/blob/4.17/OceanProject.uproject), it seems its on the correct version.

Also, the branch latest commit (0913588958134a6ca4230e37ceac1a83bfefd719) shows the last time the files were updated, the 4.18 version wasn't even released.

What error message are you receiving?

**Comment by popeyesfx** [comment]
Initially it gave me a version error saying that the plugin was for version 4.18. 
I have since downloaded the zip file and tried that and that seemed to work fine. I am not sure if the issue was related to using git desktop.

Thanks for the quick answer
