### ISSUE TITLE
BuoyantDestructible Component causes crash

### ISSUE THREAD

**Issue by infatime** [UE4-OceanProject/OceanProject#69]
Putting an Actor which has a BuoyantDestructible Component under water causes crash.

<pre>Access violation - code c0000005 (first/second chance not available)

PhysX3PROFILE_x64!physx::Scb::Body::addSpatialAcceleration() [d:\build\++ue4+release-4.18+physx_compile\sync\engine\source\thirdparty\physx\physx_3.4\source\physx\src\buffering\scbbody.h:521]
PhysX3PROFILE_x64!physx::NpRigidBodyTemplate<physx::PxRigidDynamic>::addSpatialForce() [d:\build\++ue4+release-4.18+physx_compile\sync\engine\source\thirdparty\physx\physx_3.4\source\physx\src\nprigidbodytemplate.h:370]
PhysX3PROFILE_x64!physx::NpRigidDynamic::addForce() [d:\build\++ue4+release-4.18+physx_compile\sync\engine\source\thirdparty\physx\physx_3.4\source\physx\src\nprigiddynamic.cpp:275]
UE4Editor_OceanPlugin
UE4Editor_Engine!FActorComponentTickFunction::ExecuteTickHelper<<lambda_a8128609955b5bb0ccb5da311e0c1d1a> >() [d:\build\++ue4+release-4.18+compile\sync\engine\source\runtime\engine\classes\gameframework\actor.h:3100]
UE4Editor_Engine!FActorComponentTickFunction::ExecuteTick() [d:\build\++ue4+release-4.18+compile\sync\engine\source\runtime\engine\private\components\actorcomponent.cpp:794]
UE4Editor_Engine!FTickFunctionTask::DoTask() [d:\build\++ue4+release-4.18+compile\sync\engine\source\runtime\engine\private\ticktaskmanager.cpp:273]
UE4Editor_Engine!TGraphTask<FTickFunctionTask>::ExecuteTask() [d:\build\++ue4+release-4.18+compile\sync\engine\source\runtime\core\public\async\taskgraphinterfaces.h:784]
UE4Editor_Core!FNamedTaskThread::ProcessTasksNamedThread() [d:\build\++ue4+release-4.18+compile\sync\engine\source\runtime\core\private\async\taskgraph.cpp:651]
UE4Editor_Core!FNamedTaskThread::ProcessTasksUntilQuit() [d:\build\++ue4+release-4.18+compile\sync\engine\source\runtime\core\private\async\taskgraph.cpp:560]
UE4Editor_Core!FTaskGraphImplementation::WaitUntilTasksComplete() [d:\build\++ue4+release-4.18+compile\sync\engine\source\runtime\core\private\async\taskgraph.cpp:1330]
UE4Editor_Engine!FTickTaskSequencer::ReleaseTickGroup() [d:\build\++ue4+release-4.18+compile\sync\engine\source\runtime\engine\private\ticktaskmanager.cpp:542]
UE4Editor_Engine!FTickTaskManager::RunTickGroup() [d:\build\++ue4+release-4.18+compile\sync\engine\source\runtime\engine\private\ticktaskmanager.cpp:1454]
UE4Editor_Engine!UWorld::RunTickGroup() [d:\build\++ue4+release-4.18+compile\sync\engine\source\runtime\engine\private\leveltick.cpp:760]
UE4Editor_Engine!UWorld::Tick() [d:\build\++ue4+release-4.18+compile\sync\engine\source\runtime\engine\private\leveltick.cpp:1408]
UE4Editor_UnrealEd!UEditorEngine::Tick() [d:\build\++ue4+release-4.18+compile\sync\engine\source\editor\unrealed\private\editorengine.cpp:1659]
UE4Editor_UnrealEd!UUnrealEdEngine::Tick() [d:\build\++ue4+release-4.18+compile\sync\engine\source\editor\unrealed\private\unrealedengine.cpp:396]
UE4Editor!FEngineLoop::Tick() [d:\build\++ue4+release-4.18+compile\sync\engine\source\runtime\launch\private\launchengineloop.cpp:3296]
UE4Editor!GuardedMain() [d:\build\++ue4+release-4.18+compile\sync\engine\source\runtime\launch\private\launch.cpp:166]
UE4Editor!GuardedMainWrapper() [d:\build\++ue4+release-4.18+compile\sync\engine\source\runtime\launch\private\windows\launchwindows.cpp:134]
UE4Editor!WinMain() [d:\build\++ue4+release-4.18+compile\sync\engine\source\runtime\launch\private\windows\launchwindows.cpp:210]
UE4Editor!__scrt_common_main_seh() [f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253]
kernel32
ntdll<code>

**Comment by TheZoc** [comment]
@infatime Can you provide a step by step on how to reproduce this? :)

**Comment by infatime** [comment]
Thanks for your reply. My english is not so good, if my expression is not clear, I would be happy to provide more detailed information. The steps to reproduce the problems are as follows:
1. In Content Browser, go to Content\ShipsAndExamples\Assets\Shapes, create a destructible mesh of "Shape_Cube" and enable impact damage.
2. Drag a Buoyant Destructible Actor from Modes tab into level "IslandMap" and enable simulate physics.
3. Select BuoyantDestructibleComponent in  Details panel, set property Destructible Mesh to the mesh created in step 1.
4. Click Simulate button everything is perfect, but if we move the actor placed in step 2 under the sea and run will crash ue4.

**Comment by TheZoc** [comment]
I think this should be reasonably easy to fix, but right now I can't do it.
@saschaelble , I apologize for tagging you here, but do you mind checking this? I won't have time to add a fix in a while, and maybe a simple check could prevent this crash :))

**Comment by EvoPulseGaming** [comment]
I'll give it a shot after work

**Comment by TheZoc** [comment]
Thank you!

**Comment by EvoPulseGaming** [comment]
Late to the party, I'm looking at it right now.
I see that if we run the simulation and THEN move it under the water it works fine, it only happens if you move it under water BEFORE you run the simulation

After looking it over, I keep getting errors inside of phyx code where no source is available, apart from that I don't understand why visual studio keeps saying certain variables were optimized away, when they are CLEARLY used for the add force function in physx.

Once thing I keep noticing is a bunch of null references when you start underwater, vs above. Makes no sense to me, and I'm  not sure where to look for the above vs below code....

**Comment by dotcamdev** [comment]
I'l look into this some more over the coming days as well. This component was created quite a while ago by a contributor, so there may be some issues getting it to work with the refactored PhysX code. 

Will post more info asap.

**Comment by dotcamdev** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [BuoyantDestructible Crash](https://trello.com/c/b04dYx6I/67-buoyantdestructible-crash)
