### ISSUE TITLE
Issue with compiling on 4.8.3(Mac)

### ISSUE THREAD

**Issue by ianfaris** [UE4-OceanProject/OceanProject#7]
After downloading the 4.8 branch and attempting to open the project file in 4.8.3 on Mac, I get the warning:

**Missing OceanProject Modules**

The following modules are missing or built with a different engine version:
UE4Editor-OceanPlugin.dylib
Would you like to rebuild them now?

After choosing to rebuild, an error shows that the compile failed, and that I should rebuild from source manually. Any reason this is happening?

Thanks!

**Comment by calmasacow** [comment]
I believe that library is DirectX dependent at this time. to my knowledge OpenGL is not supported. It  is in the works. Of course not there is the Metal API to talk about on mac as well.
