### ISSUE TITLE
Example Levels not Working

### ISSUE THREAD

**Issue by upgr4de03** [UE4-OceanProject/OceanProject#75]
When I attempt to load in any of the sample levels it says that I have blueprint errors and I am specifically needing the Storm level. On my attempt to load the scene it complains about the blueprints being non functional which leads to UE4 deleting them. No sky, No Buoyancy (ships just fall through water).

**Comment by dotcamdev** [comment]
Hey there, I'm in the process of fixing up little issues like this in the project, and will add it to my list. Thanks for letting me know, I should have an update ready in a couple days.

**Comment by dotcamdev** [comment]
This issue has been fixed in PR #79 that has been pushed to master just now.
