### ISSUE TITLE
Errors when migrating content to another project

### ISSUE THREAD

**Issue by ShaNexx546** [UE4-OceanProject/OceanProject#76]
Hi everyone; 

The ocean did not come 
I get too many errors Is there a video about adding to the project?

**Comment by dotcamdev** [comment]
Hey, sorry for the delay. I'm currently working on fixing this issue (among others). I should have an update ready in a couple days. Will post more info here asap

**Comment by dotcamdev** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Errors When Migrating Content to Another Project](https://trello.com/c/sw2RjOkB/68-errors-when-migrating-content-to-another-project)

**Comment by EvoPulseGaming** [comment]
There is a video in the discord faq about this now. Please read the readme for the link
