### ISSUE TITLE
LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.

### ISSUE THREAD

**Issue by NameNickInc** [UE4-OceanProject/OceanProject#81]
Hello! Very nice project, congrats! but I make a new blank c++ project in Unreal, I copy the OceanPlugin Folder from your project in my Unreal 4.19.2   \UE_4.19\Engine\Plugins Folder , the plugin is on in editor and then I migrate from your Ocean Project, island map, the BP_Ocean blueprint only in my c++ project, in editor everything works well, even when I simulate the game, but when I push in editor the little fragmentated blue cube icon(Recompiles and reloads C++ code for game system on the fly)  in toolbar, i get this 
![image](https://user-images.githubusercontent.com/39761276/40714950-b2bd959a-640c-11e8-8917-e0b7b54789c2.png)

Also if i try to package  for win 64 my project, after i mark the BP_Ocean blueprint for Exclusive nativisation, i get this
UATHelper: Packaging (Windows (64-bit)):   Parsing headers for MyProject_Testblue
UATHelper: Packaging (Windows (64-bit)):     Running UnrealHeaderTool "E:\Files\Unreal\MyProject_Testblue\MyProject_Testblue.uproject" "E:\Files\Unreal\MyProject_Testblue\Intermediate\Build\Win64\MyProject_Testblue\Development\MyProject_Testblue.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors -install
ed
UATHelper: Packaging (Windows (64-bit)):   E:/programe/UE_4.19/Engine/Plugins/OceanPlugin/Source/OceanPlugin/Classes/OceanManager.h(37) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
UATHelper: Packaging (Windows (64-bit)):   E:/programe/UE_4.19/Engine/Plugins/OceanPlugin/Source/OceanPlugin/Classes/OceanManager.h(40) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
UATHelper: Packaging (Windows (64-bit)):   E:/programe/UE_4.19/Engine/Plugins/OceanPlugin/Source/OceanPlugin/Classes/OceanManager.h(43) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
UATHelper: Packaging (Windows (64-bit)):   E:/programe/UE_4.19/Engine/Plugins/OceanPlugin/Source/OceanPlugin/Classes/OceanManager.h(46) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
UATHelper: Packaging (Windows (64-bit)):   E:/programe/UE_4.19/Engine/Plugins/OceanPlugin/Source/OceanPlugin/Classes/OceanManager.h(49) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
UATHelper: Packaging (Windows (64-bit)):   E:/programe/UE_4.19/Engine/Plugins/OceanPlugin/Source/OceanPlugin/Classes/OceanManager.h(77) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
UATHelper: Packaging (Windows (64-bit)):   E:/programe/UE_4.19/Engine/Plugins/OceanPlugin/Source/OceanPlugin/Classes/OceanManager.h(80) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
UATHelper: Packaging (Windows (64-bit)):   E:/programe/UE_4.19/Engine/Plugins/OceanPlugin/Source/OceanPlugin/Classes/OceanManager.h(83) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
UATHelper: Packaging (Windows (64-bit)):   E:/programe/UE_4.19/Engine/Plugins/OceanPlugin/Source/OceanPlugin/Classes/OceanManager.h(86) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
UATHelper: Packaging (Windows (64-bit)):   E:/programe/UE_4.19/Engine/Plugins/OceanPlugin/Source/OceanPlugin/Classes/OceanManager.h(89) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
UATHelper: Packaging (Windows (64-bit)):   E:/programe/UE_4.19/Engine/Plugins/OceanPlugin/Source/OceanPlugin/Classes/OceanManager.h(92) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
UATHelper: Packaging (Windows (64-bit)):   E:/programe/UE_4.19/Engine/Plugins/OceanPlugin/Source/OceanPlugin/Classes/OceanManager.h(95) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
UATHelper: Packaging (Windows (64-bit)):   E:/programe/UE_4.19/Engine/Plugins/OceanPlugin/Source/OceanPlugin/Classes/OceanManager.h(98) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
UATHelper: Packaging (Windows (64-bit)):   E:/programe/UE_4.19/Engine/Plugins/OceanPlugin/Source/OceanPlugin/Classes/OceanManager.h(140) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
UATHelper: Packaging (Windows (64-bit)):   E:/programe/UE_4.19/Engine/Plugins/OceanPlugin/Source/OceanPlugin/Classes/OceanManager.h(144) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
UATHelper: Packaging (Windows (64-bit)):   E:/programe/UE_4.19/Engine/Plugins/OceanPlugin/Source/OceanPlugin/Classes/OceanManager.h(148) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
UATHelper: Packaging (Windows (64-bit)):   E:/programe/UE_4.19/Engine/Plugins/OceanPlugin/Source/OceanPlugin/Classes/OceanManager.h(152) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
UATHelper: Packaging (Windows (64-bit)):   E:/programe/UE_4.19/Engine/Plugins/OceanPlugin/Source/OceanPlugin/Classes/OceanManager.h(159) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
UATHelper: Packaging (Windows (64-bit)):   E:/programe/UE_4.19/Engine/Plugins/OceanPlugin/Source/OceanPlugin/Classes/OceanManager.h(164) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
UATHelper: Packaging (Windows (64-bit)):   E:/programe/UE_4.19/Engine/Plugins/OceanPlugin/Source/OceanPlugin/Classes/OceanManager.h(169) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
UATHelper: Packaging (Windows (64-bit)):   E:/programe/UE_4.19/Engine/Plugins/OceanPlugin/Source/OceanPlugin/Classes/OceanManager.h(172) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
UATHelper: Packaging (Windows (64-bit)):   E:/programe/UE_4.19/Engine/Plugins/OceanPlugin/Source/OceanPlugin/Classes/OceanManager.h(183) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
UATHelper: Packaging (Windows (64-bit)):   E:/programe/UE_4.19/Engine/Plugins/OceanPlugin/Source/OceanPlugin/Classes/OceanManager.h(186) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
UATHelper: Packaging (Windows (64-bit)):   E:/programe/UE_4.19/Engine/Plugins/OceanPlugin/Source/OceanPlugin/Classes/OceanManager.h(189) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
UATHelper: Packaging (Windows (64-bit)):   E:/programe/UE_4.19/Engine/Plugins/OceanPlugin/Source/OceanPlugin/Classes/OceanManager.h(192) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
UATHelper: Packaging (Windows (64-bit)):   E:/programe/UE_4.19/Engine/Plugins/OceanPlugin/Source/OceanPlugin/Classes/OceanManager.h(195) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
UATHelper: Packaging (Windows (64-bit)):   E:/programe/UE_4.19/Engine/Plugins/OceanPlugin/Source/OceanPlugin/Classes/OceanManager.h(198) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
LogSlate: FSceneViewport::OnFocusLost() reason 2
UATHelper: Packaging (Windows (64-bit)):   Error: UnrealHeaderTool failed for target 'MyProject_Testblue' (platform: Win64, module info: E:\Files\Unreal\MyProject_Testblue\Intermediate\Build\Win64\MyProject_Testblue\Development\MyProject_Testblue.uhtmanifest, exit code: OtherCompilationError (5)).
PackagingResults: Error: UnrealHeaderTool failed for target 'MyProject_Testblue' (platform: Win64, module info: E:\Files\Unreal\MyProject_Testblue\Intermediate\Build\Win64\MyProject_Testblue\Development\MyProject_Testblue.uhtmanifest, exit code: OtherCompilationError (5)).
UATHelper: Packaging (Windows (64-bit)): Took 18.6336664s to run UnrealBuildTool.exe, ExitCode=5
UATHelper: Packaging (Windows (64-bit)): ERROR: Command failed (Result:5): E:\programe\UE_4.19\Engine\Binaries\DotNET\UnrealBuildTool.exe MyProject_Testblue Win64 Development -Project=E:\Files\Unreal\MyProject_Testblue\MyProject_Testblue.uproject  E:\Files\Unreal\MyProject_Testblue\MyProject_Testblue.uproject -NoUBTMakefiles  -remoteini="E:\Files\Unreal\MyPr
oject_Testblue" -skipdeploy -noxge -NoHotReload -ignorejunk. See logfile for details: 'UnrealBuildTool-2018.05.30-01.59.12.txt' 
UATHelper: Packaging (Windows (64-bit)):        (see C:\Users\Nick\AppData\Roaming\Unreal Engine\AutomationTool\Logs\E+programe+UE_4.19\UAT_Log.txt for full exception trace)
PackagingResults: Error: Command failed (Result:5): E:\programe\UE_4.19\Engine\Binaries\DotNET\UnrealBuildTool.exe MyProject_Testblue Win64 Development -Project=E:\Files\Unreal\MyProject_Testblue\MyProject_Testblue.uproject  E:\Files\Unreal\MyProject_Testblue\MyProject_Testblue.uproject -NoUBTMakefiles  -remoteini="E:\Files\Unreal\MyProject_Testblue" -skipde
ploy -noxge -NoHotReload -ignorejunk. See logfile for details: 'UnrealBuildTool-2018.05.30-01.59.12.txt' 
UATHelper: Packaging (Windows (64-bit)): AutomationTool exiting with ExitCode=5 (5)
UATHelper: Packaging (Windows (64-bit)): BUILD FAILED
PackagingResults: Error: Unknown Error
LogSlate: FSceneViewport::OnFocusLost() reason 0
LogSlate: FSceneViewport::OnFocusLost() reason 0
LogSlate: FSceneViewport::OnFocusLost() reason 2
LogSlate: FSceneViewport::OnFocusLost() reason 0
LogSlate: FSceneViewport::OnFocusLost() reason 0
LogSlate: FSceneViewport::OnFocusLost() reason 2
LogSlate: FSceneViewport::OnFocusLost() reason 0
What to do?

**Comment by NilsonFLima** [comment]
Hi there, please follow the instructions on this video I made and you should be fine! https://youtu.be/1W6Z5XnUyAI

**Comment by NameNickInc** [comment]
I want to tell you thanks. I follow your video and apply the steps and all problems are solved now, however I want to mention that in video from minute 8:15 when you right clicking on the TestOcean.uproject, in my case initially I don't have that options Generate Visual Studio project files, so I have to do extra research to find a solution for that, some solutions are only valid for diferent versions of unreal engine, for my version 4.19.2 I did the following : I copied UnrealVersionSelector.exe from C:\Program Files (x86)\Epic Games\Launcher\Engine\Binaries\Win64  to the instal directory\UE_4.19\Engine\Binaries\Win64 and then click on it and press ok, after that I was able to see that contextual menu with Generate Visual Studio project files, so maybe you put this trick in your video because I spent a lot of time, trial and error in order to figure this. I will do some modifications to sky blueprint, that colors on the curves  doesn't feel right to me, I will use a cheap shader for the sky, something unlit and with material parameter colection, I will modify horizont colors distribution for the sunset, to warms colors only in direction of the sun, in oposite direction must be cool colors in horizont. I will reduce mesh geometry are too many triangles, must be a geosphere(in 3dMax), whatever, thank you for your time and help.

**Comment by NilsonFLima** [comment]
Nice things went well. I don't have to do that extra step you mentioned and never did, since I always had Visual Studio installed in my machine. It is important to have it, since sometimes Epic will release a new engine version and all plugins need to be recompiled with Visual Studio to work, not just this one, but any other you might use in the future, since it is faster you recompile yourself than wait all developers which make plugins to do it in a timely manner. Be sure to join the Discord Server in case you encounter any other doubts. The Forum thread has it attached with user DotCam which is the author for this plugin.
