### ISSUE TITLE
Ocean bp cannot load highmap texture when launching game in linux

### ISSUE THREAD

**Issue by NilsonFLima** [UE4-OceanProject/OceanProject#82]
UE forum user Swdan said:

"guys, note that packaging and launching the game as a linux headless server results in signal 11 segmentation fault caused by ocean bp is not able to load heightmap texture. either add some "is valid" check in c++ or... something took a day to figure out"

**Comment by dotcamdev** [comment]
Ouch... That's not good.

I'll add this in when I get back home tomorrow, something came up last minute had to go to the city. I should be back tomorrow midday so will chat with you guys then.

DC

**Comment by dotcamdev** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Ocean Material Wont Load Heightmap Texture on Linux](https://trello.com/c/VW0Qo2wZ/66-ocean-material-wont-load-heightmap-texture-on-linux)

**Comment by SankaDaVinci** [comment]
Hi! Great work on the plugin! Btw the same issue is happening in my project aswell. It isn't loading the heightmap on Windows 10. On Editor looks fine but in the compiled version it does not load.

**Comment by NilsonFLima** [comment]
Going to check this tomorrow and let you know.

*Nilson Fernandes de Lima*



Em ter, 23 de abr de 2019 às 01:08, Daniel Alves <notifications@github.com>
escreveu:

**Comment by SankaDaVinci** [comment]
> Going to check this tomorrow and let you know.
> 
> *Nilson Fernandes de Lima*
> 
> 
> 
> Em ter, 23 de abr de 2019 às 01:08, Daniel Alves <notifications@github.com>
> escreveu:
> …

Thank you!

**Comment by NilsonFLima** [comment]
Could you give more details about the releases you are using?
UE4.??
Linux ??
GCC??


*Nilson Fernandes de Lima*



Em seg, 22 de abr de 2019 às 23:05, Daniel Alves <notifications@github.com>
escreveu:

**Comment by SankaDaVinci** [comment]
Hey! So I tried it in a different project and it worked. UE 4.20.3 windows 10, so ignore my comments! Thank you for the attention.
