### ISSUE TITLE
Insert Ocean Project maps into an existing project

### ISSUE THREAD

**Issue by Iremodder** [UE4-OceanProject/OceanProject#83]
Is there a way to insert all of the Ocean levels into an existing project with their assets/content correctly?

**Comment by NilsonFLima** [comment]
Please, check this video in detail and for the remaining folders you just use the Migrate function right-clicking on the original project and point at the Content folder at the destination project: https://youtu.be/1W6Z5XnUyAI

**Comment by fanlongyu** [comment]
I did what you did in the video, but finally I can't use physics handle and I can't press E to drive the boat，please help me ，thanks

**Comment by EvoPulseGaming** [comment]
Did you make sure to put E into your input settings? 
After doing that open the blueprint and replace the old Input with the new one

You can talk to us here:
https://discord.gg/zYNG45

**Comment by fanlongyu** [comment]
The e key is working, but it is blank under the sea on the map dcSkyTestMap and IslandMap

**Comment by EvoPulseGaming** [comment]
This was solved on the discord channel, if I remember correctly. Closed
