### ISSUE TITLE
Moon Appears Behind Stars

### ISSUE THREAD

**Issue by ghost** [UE4-OceanProject/OceanProject#84]
I noticed that at night the moon appears behind the stars. This should be a quick easy fix. (Hopefully)

**Comment by NilsonFLima** [comment]
We are changing in a future version a new Weather System, which will be also a separate module. Know that, the project has few user contributions and some of them abandoned in the end. While we would like to keep them, as we are planning better stuff for the future we will let it as it is. Wait for the new update soon.

**Comment by ghost** [comment]
Could I have a Discord invite? I would be honored to help out if I can.

**Comment by NilsonFLima** [comment]
Sure thing: https://discord.gg/qwESbbW

**Comment by EvoPulseGaming** [comment]
I've fixed this issue and many other issues related to the rotation of the moon, and phase angle/shadowing. I'm just finishing up the shadow rotation part then I will release this into the diftow branch, and later master. I will close this for now as the fix (only for the star/moon issue) is already in the diftow branch, the rest is to come once I clean it up
