### ISSUE TITLE
Packaging to Windows x64 success, but fail when executing

### ISSUE THREAD

**Issue by Rbn3D** [UE4-OceanProject/OceanProject#89]
Hi, I'm getting this crash at startup when running the packaged build:

![imagen](https://user-images.githubusercontent.com/4525805/47844182-ff82f800-ddc1-11e8-9c76-6122dc2bf9f6.png)

The editor seems to work fine.

Any ideas?

**Comment by Rbn3D** [comment]
My UE version is 4.20.3 (installed from epic games launcher). The packaged build is targeting Windows x64

**Comment by Rbn3D** [comment]
Also commenting about this on the forum:

https://forums.unrealengine.com/community/work-in-progress/1519072-community-project-free-ocean-water-shader?p=1547318#post1547318

https://forums.unrealengine.com/community/work-in-progress/1519072-community-project-free-ocean-water-shader?p=1547337#post1547337

**Comment by Rbn3D** [comment]
I finally managed to get it working, I had to modify some includes on the plugin itself and also install the plugin as a runtime engine plugin (so it works on packaged builds).

I did a PR that adds support to UE 4.20:
https://github.com/UE4-OceanProject/OceanProject/pull/90

Make sure you follow this guide to set it up into your project:
https://github.com/Rbn3D/OceanProject/blob/4.20/INSTALL.md

Hope it helps someone.

**Comment by EvoPulseGaming** [comment]
Thank you for your work, I am looking over your commits, I will leave a reply very shortly
