### ISSUE TITLE
package failure-win10 64bit ue4.20.3 vs2017

### ISSUE THREAD

**Issue by wwlgyy** [UE4-OceanProject/OceanProject#93]
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: begin: stack for UAT
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: === Critical error: ===
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error:
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: Fatal error!
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error:
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x00000008
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error:
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ffa4b62c181 UE4Editor-Landscape.dll!UnknownFunction []
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ffa4b5a7263 UE4Editor-Landscape.dll!UnknownFunction []
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ffa4b5a1aa2 UE4Editor-Landscape.dll!UnknownFunction []
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ffa4b5a18a4 UE4Editor-Landscape.dll!UnknownFunction []
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ffa50d83345 UE4Editor-CoreUObject.dll!UnknownFunction []
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ffa50e6b7a1 UE4Editor-CoreUObject.dll!UnknownFunction []
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ffa50e862c4 UE4Editor-CoreUObject.dll!UnknownFunction []
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ffa50e854b9 UE4Editor-CoreUObject.dll!UnknownFunction []
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ffa4be10b3c UE4Editor-UnrealEd.dll!UnknownFunction []
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ffa4be5553d UE4Editor-UnrealEd.dll!UnknownFunction []
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ffa4bcc7a8d UE4Editor-UnrealEd.dll!UnknownFunction []
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ffa4bcf88ff UE4Editor-UnrealEd.dll!UnknownFunction []
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ff6cf52e9c2 UE4Editor-Cmd.exe!UnknownFunction []
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ff6cf525968 UE4Editor-Cmd.exe!UnknownFunction []
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ff6cf525bba UE4Editor-Cmd.exe!UnknownFunction []
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ff6cf533dac UE4Editor-Cmd.exe!UnknownFunction []
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ff6cf534ce6 UE4Editor-Cmd.exe!UnknownFunction []
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ffa73628102 KERNEL32.DLL!UnknownFunction []
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ffa757bc5b4 ntdll.dll!UnknownFunction []
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error:
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: end: stack for UAT
PackagingResults: Error: begin: stack for UAT
PackagingResults: Error: === Critical error: ===
PackagingResults: Error: Fatal error!
PackagingResults: Error: Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x00000008
PackagingResults: Error: [Callstack] 0x00007ffa4b62c181 UE4Editor-Landscape.dll!UnknownFunction []
PackagingResults: Error: [Callstack] 0x00007ffa4b5a7263 UE4Editor-Landscape.dll!UnknownFunction []
PackagingResults: Error: [Callstack] 0x00007ffa4b5a1aa2 UE4Editor-Landscape.dll!UnknownFunction []
PackagingResults: Error: [Callstack] 0x00007ffa4b5a18a4 UE4Editor-Landscape.dll!UnknownFunction []
PackagingResults: Error: [Callstack] 0x00007ffa50d83345 UE4Editor-CoreUObject.dll!UnknownFunction []
PackagingResults: Error: [Callstack] 0x00007ffa50e6b7a1 UE4Editor-CoreUObject.dll!UnknownFunction []
PackagingResults: Error: [Callstack] 0x00007ffa50e862c4 UE4Editor-CoreUObject.dll!UnknownFunction []
PackagingResults: Error: [Callstack] 0x00007ffa50e854b9 UE4Editor-CoreUObject.dll!UnknownFunction []
PackagingResults: Error: [Callstack] 0x00007ffa4be10b3c UE4Editor-UnrealEd.dll!UnknownFunction []
PackagingResults: Error: [Callstack] 0x00007ffa4be5553d UE4Editor-UnrealEd.dll!UnknownFunction []
PackagingResults: Error: [Callstack] 0x00007ffa4bcc7a8d UE4Editor-UnrealEd.dll!UnknownFunction []
PackagingResults: Error: [Callstack] 0x00007ffa4bcf88ff UE4Editor-UnrealEd.dll!UnknownFunction []
PackagingResults: Error: [Callstack] 0x00007ff6cf52e9c2 UE4Editor-Cmd.exe!UnknownFunction []
PackagingResults: Error: [Callstack] 0x00007ff6cf525968 UE4Editor-Cmd.exe!UnknownFunction []
PackagingResults: Error: [Callstack] 0x00007ff6cf525bba UE4Editor-Cmd.exe!UnknownFunction []
PackagingResults: Error: [Callstack] 0x00007ff6cf533dac UE4Editor-Cmd.exe!UnknownFunction []
PackagingResults: Error: [Callstack] 0x00007ff6cf534ce6 UE4Editor-Cmd.exe!UnknownFunction []
PackagingResults: Error: [Callstack] 0x00007ffa73628102 KERNEL32.DLL!UnknownFunction []
PackagingResults: Error: [Callstack] 0x00007ffa757bc5b4 ntdll.dll!UnknownFunction []

**Comment by EvoPulseGaming** [comment]
Not enough information to really help. This is really old, and may be obsolete.
