### ISSUE TITLE
Null pointer passed at this point when loading heightmap

### ISSUE THREAD

**Issue by ghost** [UE4-OceanProject/OceanProject#99]
Hi, I recently added my heightmap to the Ocean BP (2048x2048px texture, PNG) and that caused a crash. Looking into the crash log I found that the function LoadLandscapeHeightmap(...) seemed to be a bit buggy so I debugged it and found out that here:

https://github.com/UE4-OceanProject/OceanProject/blob/7492f1e70fe4f77f4a5c8f788eefd6b8e3329b01/Plugins/OceanPlugin/Source/OceanPlugin/Private/OceanManager.cpp#L116

a nullpointer is passed. I was already wondering why there's no null pointer check but this seems to be a very unlikely problem. Would it be enough to make a null pointer check at that point or is it unusual behavior to have null pointer passed at this point?

![image](https://user-images.githubusercontent.com/8024663/58703157-0c8fb600-83a8-11e9-9951-2e56ee702317.png)

Cheers, taiBsu

EDIT: another thing which I find quite strange is that the Texture2D filename is passed very strangely. the texture's filename is "story1_hm_2048" and in debug it looks like this:

![image](https://user-images.githubusercontent.com/8024663/58703330-98094700-83a8-11e9-8164-bbeb1b0729f5.png)

**Comment by RivervdMeulen** [comment]
Hey, I'm experiencing the same thing after recently updating my project to the latest version of UE4/this plugin. The heightmap in the demo level works fine, but trying it in my level with my heightmap, Unreal immediately crashes. The weird thing is that it does work in-editor, it's only once I hit play that I get the error.

Would love to know of any fixes, if there are any available already.

Cheers!

**Comment by ghost** [comment]
Hey RiverdMeulen, I have made a workaround for this in the code. I could pass you the code so you could compile it for yourself it you want or create a pull request.

**Comment by RivervdMeulen** [comment]
Hey, it'd be great if I could get that code. Could you also create a pull request to merge it with this repo? That way it'll be fixed for everyone in future versions of the plugin.

**Comment by EvoPulseGaming** [comment]
A pull request would be great 
At the very least, post the edited code here and I can put it into the repo

**Comment by ghost** [comment]
@EvoPulseGaming I created a pull request for this at https://github.com/UE4-OceanProject/OceanProject/pull/103 . However this is just a hotfix and not guaranteed to work properly in any situation, I'm not enough into the project to be able to evaluate that. Plus, this only fixes the nullpointer thing, not the strange name behavior. I might look that up later.

@RivervdMeulen have a look at the pull request, hope that helps.

PS: I have no idea why that commit appears three times.

**Comment by EvoPulseGaming** [comment]
Any contribution is appreciated right now. I've gone ahead and approved it.
